### ISSUE TITLE
Why node-pty instead of `childpty`

### ISSUE THREAD

**Issue by basarat** [speedterm/speedterm#1]
Thanks for Open sourcing this ! :rose: ❤️ 

Quick questions: 

* Is childpty pure js https://www.npmjs.com/package/childpty 

If so why not use that instead of node-pty : https://github.com/speedterm/speedterm/blob/d4032cb4aadc26e4c827c64b0da1d17dffacf9b5/package.json#L42  

In full disclosure I need a terminal support for alm.tools https://github.com/alm-tools/alm/issues/133#issuecomment-248539599 but don't want to force people to have a working node-gyp toolchain 😢

**Comment by jkuri** [comment]
hi @basarat! thanks for your questions.

I made `childpty` package out of original https://github.com/Gottox/child_pty but compatible with `rollup`. Then I switched to `node-pty` which seems to be more recently updated and also works on Windows `powershell.exe`. Basically, Win support was the only reason to switch to `node-pty`.

Checked `alm` project and must say that I love it, I am also a heavy TypeScript user and never heard of that before. Back to your question, there are plenty of "childtty" forks around and I since now I did not notice one that works without `node-gyp`, I believe only thing that you can do is to provide package that already have compiled c++ bindings included, just like `node-sass` does. 
I strongly believe that there is no pure JS/TS package that works with pseudo terminals, also cannot imagine how that could be possible. 
Btw, let me know if you need help integrating that thing into your project.

**Comment by basarat** [comment]
> I strongly believe that there is no pure JS/TS package that works with pseudo terminals, also cannot imagine how that could be possible.

Thanks for your answer, time and kind words :heart: :rose: 

>  I believe only thing that you can do is to provide package that already have compiled c++ bindings included, just like node-sass does.

Fingers crossed that `node-pty` does that someday ❤️
